# Happy Coding!

service: weather-station-writer

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: iot
  environment:
    DYNAMODB_TABLE: !ImportValue WeatherStationTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
      - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  process:
    handler: handler.process
    reservedConcurrency: 5
    versionFunctions: false # optional, default is true
    memory: 512
    timeout: 2
    tags:
      - Key: project
        Value: weather-station